const publications = [
  {
    title: "Heterogeneity in U.S. Farms: A New Clustering by Production Potentials",
    type: "Article",
    outlet: "Agriculture 13(2): 258",
    year: 2023,
    authors: "Asif Rasool; David Abler",
    summary:
      "Agglomerative hierarchical clustering of 2,778 farming-defined counties into six groups, showing how farm size, assets, labor, output, mechanization, and government programs shape production potential across the contiguous U.S.",
    abstract:
      "This paper uses agglomerative hierarchical cluster analysis to group 2778 farming-defined counties into six clusters, revealing farm patterns across the contiguous 48 states of the United States. To understand the differences in economic performance and improve farm households' well-being, economists have endeavored to identify patterns in US farming. The US is a leading global producer and exporter of many agricultural and food products. Our primary objective is to construct a policy-relevant farm clustering to characterize agricultural homogeneity in US farms' production potential. We identify six clusters that are relatively homogeneous in five dimensions: farm size, farm assets, farm labor, farm output, degree of mechanization, and government programs. Minimizing diversity within a cluster allows for analysis of public policy changes on specific clusters and comparison of differential effects of the change across clusters.",
    link: "https://doi.org/10.3390/agriculture13020258",
  },
  {
    title: "Investing in Agribusiness Stocks and Farmland: A Boom or Bust Analysis",
    type: "Article",
    outlet: "Utah State University",
    year: 2018,
    authors: "Asif Rasool",
    summary:
      "Applied a copula-based approach to portfolio construction for agribusiness stocks and farmland, highlighting diversification benefits beyond traditional Markowitz assumptions and quantifying downside risk for investors focused on agriculture.",
    link: "https://www.proquest.com/docview/2070453070",
    abstract:
      "The study examines how boom and bust cycles shift asset composition in agricultural portfolios. Using a copula VaR framework to move beyond normality assumptions of modern portfolio theory, it quantifies downside risk and finds farmland dominates unconstrained portfolios across cycles, while restricted portfolios diversify but carry higher downside risk and volatility. Traditional Markowitz methods underestimate actual portfolio risk.",
  },
  {
    title: "Beyond Books: Estimating the Economic and Social Impact of the Livingston Parish Library",
    type: "Economic Impact Study",
    outlet: "Business Research Center, Southeastern Louisiana University",
    year: 2025,
    authors: "Asif Rasool",
    summary:
      "Hybrid input-output and benefit-transfer analysis showing how library programs ripple through jobs, output, tax revenue, and community value.",
    link: "https://livingston-parish-library-750090776627.us-central1.run.app/",
    abstract:
      "This study evaluates the economic and social value of the Livingston Parish Library using a mixed-method framework that integrates a Social Accounting Matrix (SAM)-based Input-Output model with a contingent valuation (CV) benefit transfer approach. Drawing on verified financial data and localized economic modeling, the analysis estimates both the tangible and intangible returns generated by the library for the Livingston Parish community. The results show that the library's activities support more than 158 jobs, generate $8.43 million in total economic output, and contribute $6.02 million in value added to the local economy annually. These impacts yield a conventional output multiplier of 1.32, indicating that every dollar invested in the library circulates widely through the regional economy. In addition, the library delivers an estimated $2.79 million in annual intangible benefits—including access to educational programming, technology services, cultural enrichment, and community space—based on nationally benchmarked willingness-to-pay (WTP) figures and conservative reach estimates. When these non-market benefits are incorporated, the library's expanded return-on-investment multiplier rises to 1.75, meaning that each public dollar yields $1.75 in combined economic and social value. These findings align with prior research on library valuation and reinforce the position of public libraries as high-leverage, fiscally efficient community assets. The study demonstrates that even in suburban or rural settings, libraries generate substantial returns that justify continued and expanded public support.",
  },
  {
    title: "Three Essays in Applied Economics: Topics in Agricultural Economics and Public Finance",
    type: "Dissertation",
    outlet: "Pennsylvania State University",
    year: 2024,
    authors: "Asif Rasool",
    advisors: "Advisor: Dr. Dave Abler",
    summary:
      "Doctoral dissertation covering clustering of U.S. farms, agricultural economics, and public finance, with essay one advancing the nationwide clustering of farm production potential.",
    link: "https://etda.libraries.psu.edu/files/final_submissions/29594",
    abstract:
      "Essay 1: Agglomerative hierarchical clustering of 2,778 farming-defined counties into six clusters to capture production potential across the contiguous U.S., enabling policy-relevant analysis of farm size, assets, labor, output, mechanization, and government programs. Essay 2: Built comprehensive county-level datasets to model climate change impacts on five livestock types (beef cows, milk cows, layer chickens, broiler chickens, hogs) using OLS and fixed effects with inventory shares; projected 2070 outcomes via climate models, finding effects depend on livestock type and geography. Essay 3: Identified a negative association between public transit funding and private vehicle use using propensity score matching, genetic matching, and diff-in-diff on county and household panels (NHTS, NTD, Census), showing increased transit funding reduces vehicle miles traveled by roughly 6% at both county and household levels.",
  },
  {
    title: "Evaluating the Revenue and Policy Implications of Comprehensive Tax Reform Under New Mexico Senate Bill 105 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: " Lucinda Sydow; Pedro Clavijo; Sara Grubbs; Asif Rasool",
    summary:
      "Assessed SB 105’s overhaul of New Mexico’s tax code, weighing repealed credits and lower PIT, CIT, and GRT rates against equity, simplicity, and revenue stability.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0105_333.pdf",
    abstract:
      "This fiscal impact report examines the proposed wholesale overhaul of New Mexico's tax code under SB-105, which would repeal numerous tax acts and credits while simultaneously reducing statutory rates for key taxes such as personal income tax (PIT), corporate income tax (CIT), gross receipts tax (GRT), and compensating tax. The legislation eliminates the Estate Tax Act, Alternative Fuel Tax Act, Insurance Premium Tax Act, rural job tax credits, and several energy and research-related incentives. At the same time, SB-105 compresses the PIT schedule from five brackets to three, reduces GRT and compensating tax rates, lowers the capital gains deduction, and introduces a GRT exemption for nonprofit donations. Using historical return data and forward-looking economic forecasts, the report evaluates the net revenue consequences across major funds. Although repealing credits offsets a portion of the losses, the projected reductions in PIT, CIT, and GRT collections yield substantial net declines. The analysis highlights key trade-offs: reforms aimed at simplicity and uniformity may diminish vertical and horizontal equity and weaken targeted development incentives, while also creating uncertainty for local governments dependent on GRT revenues. The report recommends a phased approach to implementation to allow monitoring of behavioral responses and to provide sufficient time for administrative systems to adapt.",
  },
  {
    title: "Comprehensive Tax Code Revisions and Fiscal Effects under New Mexico HB 0252 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Pedro Clavijo; Sara Grubbs; Lucinda Sydow; Asif Rasool",
    summary:
      "Modeled HB 252’s WFTC expansion with microsimulation, showing progressive gains for low-income households alongside larger general-fund obligations and admin lift.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/HB0252_333.pdf",
    abstract:
      "This fiscal impact report evaluates the revenue, distributional, and administrative effects of House Bill 252, which proposes significant changes to New Mexico's Working Families Tax Credit (WFTC) and other related refundable tax programs. HB 252 expands WFTC eligibility, increases credit amounts for low- and moderate-income households, and introduces new adjustments tied to federal Earned Income Tax Credit (EITC) parameters. The legislation also modifies residency and filing requirements intended to streamline access for qualifying taxpayers while reducing administrative burdens. Using historical tax return data and microsimulation modeling, the analysis estimates the fiscal effects across multiple tax years, projecting substantial increases in general-fund obligations due to enhanced refundability. The distributional assessment indicates that the majority of benefits accrue to households in the lowest income brackets, improving progressivity and reducing effective tax burdens for working families. However, the report also notes potential administrative challenges, including implementation costs, taxpayer outreach needs, and coordination with federal EITC updates. Overall, HB 252 strengthens New Mexico's portfolio of anti-poverty tax credits but introduces ongoing fiscal commitments that require careful budgeting and sustained monitoring of taxpayer behavior and program participation.",
  },
  {
    title: "Assessing the Revenue Effects of a Capital Gains Deduction Increase Under Senate Bill 64 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool",
    summary:
      "Evaluated SB 64’s jump to a 60% capital gains deduction, highlighting front-loaded PIT losses, high-income concentration of benefits, and vertical equity trade-offs.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0064_333.pdf",
    abstract:
      "This fiscal impact report analyzes Senate Bill 64, which proposes increasing New Mexico's capital gains deduction from 40 percent to 60 percent for qualifying taxpayers. The bill aims to promote investment, savings, and economic activity by lowering the effective tax burden on realized gains. Using historical tax return data and forecasted capital gains realizations, the report estimates the bill's fiscal consequences for the general fund. The analysis projects material reductions in personal income tax revenue beginning in FY 2025, with the magnitude of losses influenced by volatility in capital gains markets and taxpayer behavior. While the proposed deduction may enhance competitiveness relative to neighboring states and potentially encourage long-term investment, the report highlights important trade-offs: revenue losses are front-loaded, benefits are concentrated among higher-income filers, and the policy significantly reduces vertical equity. The analysis concludes that although SB 64 may generate certain economic incentives, its fiscal costs are substantial and should be weighed against the state's ongoing budgetary commitments and needs.",
  },
  {
    title: "Economic and Fiscal Implications of the Proposed Advanced Energy Equipment Income Tax Credit Under House Bill 274 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool; Lucinda Sydow",
    summary:
      "Reviewed HB 274’s 20% credit for advanced energy equipment, noting large potential general-fund costs and oversight needs as projects scale.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/HB0274_333.pdf",
    abstract:
      "This fiscal impact report evaluates House Bill 274, which proposes creating a new nonrefundable income tax credit for investments in advanced energy manufacturing equipment used in the production of hydrogen, renewable energy technologies, grid modernization components, and related clean-energy systems. The bill establishes a credit equal to 20 percent of qualified equipment costs, capped at $25 million per taxpayer per year, with a statewide annual program limit of $75 million. Using historical industry data, investment trends, and New Mexico's existing portfolio of energy-related incentives, the analysis estimates the potential revenue impact beginning in FY 2026. Although uptake is uncertain due to taxpayer self-selection and the scale of eligible projects, the report anticipates significant reductions to the general fund as projects ramp up, partially offset by long-run economic development gains. The analysis highlights key considerations related to administrative capacity, verification of equipment eligibility, interaction with federal incentives under the Inflation Reduction Act, and the risk of concentrated benefits among large corporate taxpayers. While HB 274 may stimulate high-value capital investment in emerging energy industries, its fiscal cost is substantial, and the report recommends strong oversight mechanisms to ensure compliance, prevent credit stacking, and support evaluation of the program's long-term economic returns.",
  },
  {
    title: "Revenue, Apportionment, and Competitiveness Effects of Corporate Income Tax Restructuring Under Senate Bill 181 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool; Lucinda Sydow",
    summary:
      "Modeled SB 181’s single-rate CIT with throwback repeal, flagging large revenue losses and exposure to income shifting despite competitiveness gains.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0181_333.pdf",
    abstract:
      "This fiscal impact report evaluates Senate Bill 181, which proposes major changes to New Mexico's corporate income tax (CIT) structure, apportionment rules, and multi-state taxation framework. SB 181 consolidates the current three-tier CIT rate schedule into a single rate of 5.9 percent for taxable income above $500,000, repeals the sales-only apportionment election, and eliminates the statewide throwback rule. Using historical corporate tax records and economic forecasting models, the analysis estimates substantial general-fund revenue losses beginning in FY 2025, driven primarily by removing the throwback rule, which currently attributes certain out-of-state sales back to New Mexico. Although the bill is expected to improve tax competitiveness for multi-state firms and reduce compliance burdens associated with apportionment elections and throwback calculations, the report notes significant fiscal risks, including increased exposure to income-shifting and reduced stability of the corporate tax base. The analysis concludes that SB 181 represents a structural shift toward a more nationally aligned CIT system, but its sizeable revenue impact necessitates careful monitoring, particularly given the state's dependence on CIT revenues from a small number of large corporate taxpayers.",
  },
  {
    title: "Fiscal and Infrastructure Funding Effects of EV/PHEV Registration Fees Under Senate Bill 0183 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool",
    summary:
      "Estimated SB 0183’s EV and PHEV registration fees, balancing road-fund revenue gains against clean-transport adoption and admin costs.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0183_333.pdf",
    abstract:
      "This fiscal impact report assesses the implications of SB 0183, which establishes a new annual registration fee for electric vehicles (EVs) and plug-in hybrid electric vehicles (PHEVs) registered in New Mexico. Specifically, the bill sets a $120 annual fee for EVs and a $60 fee for PHEVs (with gross vehicle weight under 26,000 lbs), effective January 1, 2025. Based on projected growth trends in New Mexico's EV/PHEV market, the report estimates that the new fee will generate increasing revenue for the Motor Vehicle Suspense Fund and subsequent allocations to the State Road Fund and Transportation Project Fund across FY 2025 to FY 2028 - rising to an estimated $5.7 million by FY 2028 under base assumptions. The analysis assumes continued high year-over-year growth in EV adoption, extrapolating from historical increases between 2016 and 2022. The report highlights the need for this fee in light of declining gasoline tax revenue - traditionally used to fund road maintenance and infrastructure - as EV usage rises. However, the report also flags potential tensions between infrastructure funding goals and environmental/climate-policy incentives: the fee could dampen EV adoption or be seen as counter to clean-energy goals. Administrative costs associated with implementing the fee and updating the vehicle registry system are also estimated, with one-time development costs and ongoing staffing/IT resource needs detailed. Overall, SB 0183 provides a revenue-raising mechanism aimed at preserving transportation infrastructure funding in a vehicle fleet transitioning toward electrification. But the report underscores trade-offs between fiscal stability, administrative burden, and the state's broader environmental objectives - recommending careful evaluation of EV market growth assumptions and ongoing monitoring of fee effectiveness.",
  },
  {
    title: "Expanding Access to the Solar Market Development Income Tax Credit Under Senate Bill 121 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool",
    summary:
      "Reviewed SB 121’s expanded solar credit caps and tribal eligibility, noting recurring revenue losses and equity/environmental trade-offs.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0121_333.pdf",
    abstract:
      "This fiscal impact analysis reviews SB 121, which amends the existing New Solar Market Development Income Tax Credit (NSMD-ITC) under New Mexico law. The bill broadens eligibility to include leased residences, businesses, or agricultural enterprises owned by federally recognized Indian nations, tribes, or pueblos - a correction of prior exclusions for tribal lands. SB 121 also raises the cap on the aggregate amount of credits that may be certified: for calendar years 2020-2023, it allows an additional $20 million in credits to enable retroactive relief for applicants previously excluded by the statutory cap. Beginning in calendar year 2024, the annual certification cap increases from $12 million to $30 million, reflecting growing demand for solar installations. Using estimates of solar installation costs, expected payback periods, and observed growth in solar adoption, the report projects recurring general-fund revenue losses. The analysis highlights that while the expanded credit promotes environmental policy objectives, supports increased solar deployment, and enhances horizontal equity by including tribal-owned properties, it also represents a significant long-term tax expenditure. The report raises considerations about the trade-off between environmental and equity goals versus state fiscal capacity - recommending that deployment progress and uptake rates be monitored closely to assess the sustainability of the program.",
  },
  {
    title: "Fiscal Evaluation of the Energy Storage System Income Tax Credit Under House Bill 73 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool",
    summary:
      "Analyzed HB 73’s storage credit caps and modest early uptake, noting small recurring GF losses and admin updates needed for certification.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/HB0073_333.pdf",
    abstract:
      "This fiscal impact report assesses the proposed creation of an \"Energy Storage System Income Tax Credit\" via HB 73, which would allow taxpayers in New Mexico to claim a credit equal to 40% of the purchase and installation costs of a certified energy storage system on residential, commercial, industrial, or agricultural property. The credit is capped at $5,000 for residential installations and $150,000 for commercial, industrial, or agricultural installations, with a statewide annual cap of $4 million in certified credits. Under base-case assumptions, the report projects small but recurring reductions in general-fund revenue due to early-stage market adoption. The analysis identifies policy and administrative considerations, recommending careful monitoring and potential sunset or review to ensure fiscal sustainability and alignment with broader tax and energy goals.",
  },
  {
    title: "Fiscal and Incentive Effects of the Rail Infrastructure Income Tax Credit Under Senate Bill 28 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool",
    summary:
      "Estimated SB 28’s rail credit uptake and modest GF costs, noting complexity of certifying eligible railroad expenditures and tax-code placement.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0028_333.pdf",
    abstract:
      "This fiscal impact report analyzes Senate Bill 28, which establishes a new Rail Infrastructure Income Tax Credit for qualified new rail infrastructure expenditures and reconstruction/replacement expenditures by eligible railroads. Under the proposed law, the credit equals 50% of eligible expenditures, subject to annual certification limits by the New Mexico Department of Transportation. The report projects modest near-term general-fund costs, recognizing that the high cost and specialized nature of railroad projects make widespread uptake unlikely. The analysis highlights policy and administrative concerns: the complexity of certifying eligible expenditures, the narrow target group, and placement of the credit under the Personal Income Tax Act despite its focus on corporate entities.",
  },
  {
    title: "Allocating Motor Vehicle Excise Tax Revenue: Fiscal and Infrastructure Impacts of Senate Bill 184 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool; Lucinda Sydow",
    summary:
      "Analyzed SB 184’s MVEX redistribution, projecting large GF losses offset by higher road-fund revenues and modest implementation costs.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/SB0184_333.pdf",
    abstract:
      "This fiscal impact report analyzes the effects of SB 184, which restructures the distribution of revenues from the state's Motor Vehicle Excise Tax (MVEX). Under the proposed legislation, 75% of MVEX proceeds would be allocated to the State Road Fund and 25% to the Transportation Project Fund, replacing the current split that sends portions to the General Fund. Using the December 2023 consensus MVEX revenue forecast, the analysis projects significant recurring shifts beginning FY 2025, with notable reductions to the General Fund and increases to transportation funds. The report highlights alignment of revenue with road-related expenditures while noting reduced fiscal flexibility for other priorities and modest implementation costs for system updates.",
  },
  {
    title: "Long-Term Corporate Tax Implications of Extending Single-Sales-Factor Apportionment for Electric Generation Under House Bill 118 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool; Lucinda Sydow",
    summary:
      "Evaluated HB 118’s permanent single-sales-factor for generation firms, noting modest near-term losses but embedded preference and equity concerns.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/HB0118_333.pdf",
    abstract:
      "This fiscal impact report assesses House Bill 118, which proposes to remove the sunset date from the existing provision allowing certain electricity-generation facilities to permanently use a single-sales-factor formula for corporate income tax apportionment. The analysis finds modest General Fund impacts in the near term but flags erosion of horizontal equity and growing revenue risk as more generation projects come online and sell output out of state.",
  },
  {
    title: "Fiscal and Environmental Implications of the Clean Car Income Tax Credit Package Under House Bill 140 (2024)",
    type: "Fiscal Impact Report",
    outlet: "New Mexico Taxation and Revenue Department",
    year: 2024,
    authors: "Asif Rasool",
    summary:
      "Modeled HB 140’s EV/PHEV and charger credits through 2029, showing rising GF losses under optimistic adoption and sizable IT/admin needs.",
    link: "https://www.nmlegis.gov/Sessions/24%20Regular/AgencyAnalysis/HB0140_333.pdf",
    abstract:
      "This fiscal impact report evaluates HB 140, which proposes refundable credits for purchases or leases of EVs, PHEVs, fuel cell vehicles, and charging units for individuals and corporations in New Mexico. Using historic EV/PHEV adoption data and growth projections, the report estimates recurring General Fund revenue losses under optimistic market scenarios and details administrative requirements such as form changes, IT system modifications, and staffing for certification and compliance.",
  },
];

export default function Publications() {
  const orderedPublications = [...publications].sort((a, b) => (b.year || 0) - (a.year || 0));
  const years = [...new Set(orderedPublications.map((p) => p.year))].sort((a, b) => b - a);

  return (
    <div className="publications-view">
      <section className="page-section">
        <div className="section-heading">
          <div>
            <h2>Publications</h2>
            <p>Peer-reviewed articles, dissertation, and applied reports in one place.</p>
          </div>
          <a
            className="badge badge-link"
            href="https://scholar.google.com/citations?user=rd3ut40AAAAJ"
            target="_blank"
            rel="noreferrer"
            aria-label="Open Google Scholar profile"
          >
            View Google Scholar
          </a>
        </div>

        <div className="timeline publications-timeline">
          {years.map((year) => (
            <div key={year} className="timeline__year-group">
              <div className="timeline__year-label">{year}</div>
              {orderedPublications
                .filter((item) => item.year === year)
                .map((item) => (
                  <article key={item.title} className="timeline__item publication-card">
                    <div className="badge badge--gold">{item.type}</div>
                    <h3>{item.title}</h3>
                    <p className="muted">{item.outlet} • {item.year}</p>
                    {item.authors && <p className="muted">Authors: {item.authors}</p>}
                    {item.advisors && <p className="muted">{item.advisors}</p>}
                    <p>{item.summary}</p>
                    {item.abstract && <p className="muted">{item.abstract}</p>}
                    {item.link && (
                      <div className="card-actions">
                        <a
                          className="badge badge-link"
                          href={item.link}
                          target="_blank"
                          rel="noreferrer"
                          aria-label={`Open ${item.title}`}
                        >
                          Read publication
                        </a>
                      </div>
                    )}
                  </article>
                ))}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
