import { useEffect, useState } from "react";

const FIR_FILE_URL = "/FIR%20Abstracts.txt";
const FIR_ENTRY_PATTERN =
  "\\s*(?:Title\\r?\\n)?([^\\r\\n]+)\\r?\\n(?:\\r?\\n)+(?:Authors\\r?\\n)?([^\\r\\n]+)\\r?\\n(?:\\r?\\n)+Abstract\\r?\\n(?:\\r?\\n)*([\\s\\S]*?)(?=\\r?\\n(?:Title\\r?\\n)?[^\\r\\n]+\\r?\\n(?:\\r?\\n)+(?:Authors\\r?\\n)?[^\\r\\n]+\\r?\\n(?:\\r?\\n)+Abstract|$)";
const FIR_OUTLET = "New Mexico Taxation and Revenue Department";

const staticPublications = [
  {
    title: "Heterogeneity in U.S. Farms: A New Clustering by Production Potentials",
    type: "Article",
    outlet: "Agriculture 13(2): 258",
    year: 2023,
    authors: "Asif Rasool; David Abler",
    summary:
      "Agglomerative hierarchical clustering of 2,778 farming-defined counties into six groups, showing how farm size, assets, labor, output, mechanization, and government programs shape production potential across the contiguous U.S.",
    abstract:
      "This paper uses agglomerative hierarchical cluster analysis to group 2778 farming-defined counties into six clusters, revealing farm patterns across the contiguous 48 states of the United States. To understand the differences in economic performance and improve farm households' well-being, economists have endeavored to identify patterns in US farming. The US is a leading global producer and exporter of many agricultural and food products. Our primary objective is to construct a policy-relevant farm clustering to characterize agricultural homogeneity in US farms' production potential. We identify six clusters that are relatively homogeneous in five dimensions: farm size, farm assets, farm labor, farm output, degree of mechanization, and government programs. Minimizing diversity within a cluster allows for analysis of public policy changes on specific clusters and comparison of differential effects of the change across clusters.",
    link: "https://doi.org/10.3390/agriculture13020258",
  },
  {
    title: "Investing in Agribusiness Stocks and Farmland: A Boom or Bust Analysis",
    type: "Article",
    outlet: "Utah State University",
    year: 2018,
    authors: "Asif Rasool",
    summary:
      "Applied a copula-based approach to portfolio construction for agribusiness stocks and farmland, highlighting diversification benefits beyond traditional Markowitz assumptions and quantifying downside risk for investors focused on agriculture.",
    link: "https://www.proquest.com/docview/2070453070",
    abstract:
      "The study examines how boom and bust cycles shift asset composition in agricultural portfolios. Using a copula VaR framework to move beyond normality assumptions of modern portfolio theory, it quantifies downside risk and finds farmland dominates unconstrained portfolios across cycles, while restricted portfolios diversify but carry higher downside risk and volatility. Traditional Markowitz methods underestimate actual portfolio risk.",
  },
  {
    title: "Beyond Books: Estimating the Economic and Social Impact of the Livingston Parish Library",
    type: "Economic Impact Study",
    outlet: "Business Research Center, Southeastern Louisiana University",
    year: 2025,
    authors: "Asif Rasool",
    summary:
      "Hybrid input-output and benefit-transfer analysis showing how library programs ripple through jobs, output, tax revenue, and community value.",
    link: "https://livingston-parish-library-750090776627.us-central1.run.app/",
    abstract:
      "This study evaluates the economic and social value of the Livingston Parish Library using a mixed-method framework that integrates a Social Accounting Matrix (SAM)-based Input-Output model with a contingent valuation (CV) benefit transfer approach. Drawing on verified financial data and localized economic modeling, the analysis estimates both the tangible and the intangible returns generated by the library for the Livingston Parish community. The results show that the library's activities support more than 158 jobs, generate $8.43 million in total economic output, and contribute $6.02 million in value added to the local economy annually. These impacts yield a conventional output multiplier of 1.32, indicating that every dollar invested in the library circulates widely through the regional economy. In addition, the library delivers an estimated $2.79 million in annual intangible benefits—including access to educational programming, technology services, cultural enrichment, and community space—based on nationally benchmarked willingness-to-pay (WTP) figures and conservative reach estimates. When these non-market benefits are incorporated, the library's expanded return-on-investment multiplier rises to 1.75, meaning that each public dollar yields $1.75 in combined economic and social value. These findings align with prior research on library valuation and reinforce the position of public libraries as high-leverage, fiscally efficient community assets. The study demonstrates that even in suburban or rural settings, libraries generate substantial returns that justify continued and expanded public support.",
  },
  {
    title: "Putting the Cart Before the Horse: An Accidental Journey to Better Human-Computer Interaction",
    type: "HCI Case Study",
    outlet: "Business Research Center, Southeastern Louisiana University",
    year: 2025,
    authors: "Asif Rasool",
    summary:
      "Documents the SmartField-LA redesign, applying structured needfinding, heuristic reviews, personas, and iterative prototypes so strawberry disease diagnostics feel intuitive for farmers, gardeners, and educators.",
    link: "/BRC%20HCI%20Project.pdf",
    abstract:
      "SmartField-LA, a deep-learning mobile app that flags strawberry plant diseases from photos, initially shipped without a true Human-Computer Interaction process. This project retrofits that workflow: six in-situ interviews with Business Research Center staff revealed friction around lighting, icon meaning, and result interpretation; complementary heuristic reviews exposed inconsistent terminology and clutter. Synthesizing the findings into themes of clarity, feedback, and environmental adaptability, the report builds personas, brainstorms interface directions (including a field/dark mode), and delivers low-fidelity prototypes with guided navigation, labeled controls, and step-by-step instructions. The outcome is a practical UX roadmap that keeps the machine-learning core while making diagnostic actions faster, clearer, and more reliable in outdoor conditions.",
  },
  {
    title: "Three Essays in Applied Economics: Topics in Agricultural Economics and Public Finance",
    type: "Dissertation",
    outlet: "Pennsylvania State University",
    year: 2024,
    authors: "Asif Rasool",
    advisors: "Advisor: Dr. Dave Abler",
    summary:
      "Doctoral dissertation covering clustering of U.S. farms, agricultural economics, and public finance, with essay one advancing the nationwide clustering of farm production potential.",
    link: "https://etda.libraries.psu.edu/files/final_submissions/29594",
    abstract:
      "Essay 1: Agglomerative hierarchical clustering of 2,778 farming-defined counties into six clusters to capture production potential across the contiguous U.S., enabling policy-relevant analysis of farm size, assets, labor, output, mechanization, and government programs. Essay 2: Built comprehensive county-level datasets to model climate change impacts on five livestock types (beef cows, milk cows, layer chickens, broiler chickens, hogs) using OLS and fixed effects with inventory shares; projected 2070 outcomes via climate models, finding effects depend on livestock type and geography. Essay 3: Identified a negative association between public transit funding and private vehicle use using propensity score matching, genetic matching, and diff-in-diff on county and household panels (NHTS, NTD, Census), showing increased transit funding reduces vehicle miles traveled by roughly 6% at both county and household levels.",
  },
];

export default function Publications() {
  const [firPublications, setFirPublications] = useState([]);

  useEffect(() => {
    let isMounted = true;

    const loadFirAbstracts = async () => {
      try {
        const response = await fetch(FIR_FILE_URL);
        if (!response.ok) {
          throw new Error(`Failed to fetch FIR abstracts (${response.status})`);
        }
        const text = await response.text();
        if (!isMounted) {
          return;
        }
        setFirPublications(transformFirText(text));
      } catch (error) {
        console.error("Unable to load FIR abstracts", error);
      }
    };

    loadFirAbstracts();

    return () => {
      isMounted = false;
    };
  }, []);

  const orderedPublications = [...staticPublications, ...firPublications].sort((a, b) => (b.year || 0) - (a.year || 0));
  const years = [...new Set(orderedPublications.map((p) => p.year).filter(Boolean))].sort((a, b) => b - a);

  return (
    <div className="publications-view">
      <section className="page-section">
        <div className="section-heading">
          <div>
            <h2>Publications</h2>
            <p>Peer-reviewed articles, dissertation, and applied reports in one place.</p>
          </div>
          <a
            className="badge badge-link"
            href="https://scholar.google.com/citations?user=rd3ut40AAAAJ"
            target="_blank"
            rel="noreferrer"
            aria-label="Open Google Scholar profile"
          >
            View Google Scholar
          </a>
        </div>

        <div className="timeline publications-timeline">
          {years.map((year) => (
            <div key={year} className="timeline__year-group">
              <div className="timeline__year-label">{year}</div>
              {orderedPublications
                .filter((item) => item.year === year)
                .map((item) => (
                  <article key={item.title} className="timeline__item publication-card">
                    <div className="badge badge--gold">{item.type}</div>
                    <h3>{item.title}</h3>
                    <p className="muted">
                      {item.outlet} · {item.year}
                    </p>
                    {item.authors && <p className="muted">Authors: {item.authors}</p>}
                    {item.advisors && <p className="muted">{item.advisors}</p>}
                    {renderParagraphs(item.summary, undefined, `${item.title}-summary`)}
                    {renderParagraphs(item.abstract, "muted", `${item.title}-abstract`)}
                    {item.link && (
                      <div className="card-actions">
                        <a
                          className="badge badge-link"
                          href={item.link}
                          target="_blank"
                          rel="noreferrer"
                          aria-label={`Open ${item.title}`}
                        >
                          Read publication
                        </a>
                      </div>
                    )}
                  </article>
                ))}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}

function transformFirText(rawText) {
  const entries = parseFirAbstractEntries(rawText);
  const meta = parseApaBibliography(rawText);

  if (entries.length && meta.length && entries.length !== meta.length) {
    console.warn(`FIR abstracts (${entries.length}) and bibliography (${meta.length}) count mismatch.`);
  }

  return entries.map((entry, index) => {
    const metaEntry = meta[index] || {};
    const isTaxExpenditure = entry.title.toLowerCase().includes("tax expenditure report");

    return {
      title: entry.title,
      type: isTaxExpenditure ? "Tax Expenditure Report" : "Fiscal Impact Report",
      outlet: FIR_OUTLET,
      year: metaEntry.year || (isTaxExpenditure ? 2023 : 2024),
      authors: entry.authors,
      summary: entry.summary,
      abstract: entry.abstract,
      link: metaEntry.link,
    };
  });
}

function parseFirAbstractEntries(rawText) {
  if (!rawText) {
    return [];
  }

  const cutoffIndex = rawText.indexOf("Here is a");
  const scope = cutoffIndex === -1 ? rawText : rawText.slice(0, cutoffIndex);
  const regex = new RegExp(FIR_ENTRY_PATTERN, "g");
  const entries = [];
  let match;

  while ((match = regex.exec(scope))) {
    const paragraphs = splitParagraphs(match[3]);
    const [summary, ...details] = paragraphs;

    entries.push({
      title: match[1].trim(),
      authors: match[2].trim(),
      summary: summary || "",
      abstract: details.length ? details : undefined,
    });
  }

  return entries;
}

function parseApaBibliography(rawText) {
  if (!rawText) {
    return [];
  }

  const sections = rawText.split(/\r?\n---\r?\n/);
  const apaSection = sections[1] || "";
  const lines = apaSection.split(/\r?\n/);
  const entries = [];
  let currentYear;

  for (const line of lines) {
    const yearMatch = line.match(/\((\d{4})\)/);
    if (yearMatch) {
      currentYear = Number(yearMatch[1]);
    }

    const linkMatch = line.match(/\[(https?:[^\]]+)\]/);
    if (linkMatch) {
      entries.push({
        year: currentYear,
        link: linkMatch[1],
      });
      currentYear = undefined;
    }
  }

  return entries;
}

function splitParagraphs(text) {
  return text
    .split(/\r?\n\r?\n/)
    .map((segment) => segment.replace(/\s+/g, " ").trim())
    .filter(Boolean);
}

function renderParagraphs(content, className, keyPrefix) {
  if (!content) {
    return null;
  }

  const paragraphs = Array.isArray(content) ? content : [content];

  return paragraphs.map((paragraph, index) => (
    <p key={`${keyPrefix}-${index}`} className={className}>
      {paragraph}
    </p>
  ));
}
